### ISSUE TITLE
KeyError thrown when stream cannot be found on server

### ISSUE THREAD

**Issue by mill1000** [happyleavesaoc/python-snapcast#63]
Snapcast is issuing `Stream.OnUpdate` notifications (https://github.com/badaix/snapcast/issues/1205)  for input-only streams (i.e. streams with `codec=null`). These stream are not present in the `Server.GetStatus` response which causes a KeyError to be thrown when python-snapcast attempts to lookup the stream by its name here:
https://github.com/happyleavesaoc/python-snapcast/blob/9c8f97cea23015ab2414e9eee43926eca5878634/snapcast/control/server.py#L403-L406

While the bug should be fixed on the server side, I think it would also be good practice to catch exception and handling it gracefully.

```
ERROR: Fatal error: protocol.data_received() call failed.
protocol: <snapcast.control.protocol.SnapcastProtocol object at 0x7effa4256090>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/net/wyseguy/mnt/ssd/projects/snapcast-monitor/.venv/lib/python3.11/site-packages/snapcast/control/protocol.py", line 50, in data_received
    self.handle_data(item)
  File "/net/wyseguy/mnt/ssd/projects/snapcast-monitor/.venv/lib/python3.11/site-packages/snapcast/control/protocol.py", line 57, in handle_data
    self.handle_notification(data)
  File "/net/wyseguy/mnt/ssd/projects/snapcast-monitor/.venv/lib/python3.11/site-packages/snapcast/control/protocol.py", line 69, in handle_notification
    self._callbacks.get(data.get('method'))(data.get('params'))
  File "/net/wyseguy/mnt/ssd/projects/snapcast-monitor/.venv/lib/python3.11/site-packages/snapcast/control/server.py", line 405, in _on_stream_update
    self._streams[data.get('id')].update(data.get('stream'))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'upnp-bedroom'
WARNING: could not send request
```

**Comment by luar123** [comment]
Basically we could check if the stream id is in self._streams and ignore it if it isn't. Could there be any use case where we get an valid update for an unknown stream?

**Comment by mill1000** [comment]
> Could there be any use case where we get a valid update for an unknown stream?

Hard to say, perhaps it could be an indication that the server state needs to be synchronized? (Except of course in the case of the referenced bug in Snapcast)

**Comment by luar123** [comment]
Just tried it and if a stream is added by Stream.AddStream no Server.OnUpdate notification is send. So there could be streams that are not known to the client (the android app needs to be restarted as well to see this new stream). However, I would consider this a bug in the server implementation.

I see two solutions:
1. ignore all unknown streams and hope that the server will get a fix
2. synchronize the server state whenever there is an update for an unknown stream.

In case of 2. we need to filter `codec=null` streams, otherwise there will be tons of unnecessary update requests to the server. Could you verify that `codec=null` is included in the Stream.OnUpdate message?

**Comment by mill1000** [comment]
Option 2 would make sense to me. Filtering "codec=null” would only be necessary until the upstream bug is fixed
